version: "3.3"

services:
  dev:
    container_name: parachain-totem-lego-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/parachain-totem-lego-node
    ports:
      - "30333:30333"
      - "40333:40333"
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "9945:9945"
      - "9934:9934"
      - "9616:9616"
    environment:
      - CARGO_HOME=/var/www/parachain-totem-lego-node/.cargo
    volumes:
      - .:/var/www/parachain-totem-lego-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release -p parachain-totem-lego-node && ./target/release/parachain-totem-lego-node --dev --tmp"
